# Generated by Django 2.0.3 on 2018-04-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rating',
            field=models.PositiveIntegerField(default='500'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.PositiveIntegerField(default='500'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='total_earned',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
