# Generated by Django 2.0.3 on 2018-04-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180401_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skill_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_t1o_set', to='student.Skill'),
        ),
    ]
