# Generated by Django 2.0.3 on 2018-04-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_question_skill_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills_opened',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_t9o_set', to='student.Skill'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills_allowed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_t0o_set', to='student.Skill'),
        ),
    ]
