# Generated by Django 2.0.3 on 2018-04-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180401_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skills_opened',
        ),
        migrations.AddField(
            model_name='student',
            name='skills_opened',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_t9o_set', to='student.Skill'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skills_allowed',
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills_allowed',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_t0o_set', to='student.Skill'),
        ),
    ]
