# Generated by Django 2.0.3 on 2018-04-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180401_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skills_opened',
            field=models.ManyToManyField(blank=True, related_name='rel_t9o_set', to='student.Skill'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skills_allowed',
            field=models.ManyToManyField(blank=True, related_name='rel_t0o_set', to='student.Skill'),
        ),
    ]
