# Generated by Django 2.0.3 on 2018-04-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180401_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.PositiveIntegerField(default='200000')),
                ('skill_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Skill')),
            ],
        ),
    ]
