# Generated by Django 2.0.3 on 2018-04-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180402_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='skill_related',
        ),
        migrations.AddField(
            model_name='courses',
            name='skill_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel1_t1o_set', to='student.Skill'),
        ),
    ]
