# Generated by Django 2.0.3 on 2018-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180402_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cost',
            field=models.PositiveIntegerField(default='20000'),
        ),
    ]
